name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["7.3", "7.4", "8.0", "8.1"]
                symfony: ["5.3.*", "5.4.*", "6.0.*"]
                exclude:
                    - symfony: "6.0.*"
                      php: "7.3"
                    - symfony: "6.0.*"
                      php: "7.4"

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex"
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    composer config minimum-stability "dev"
                    composer config prefer-stable true

            -
                name: Install dependencies
                run: composer update

            -
                name: Composer validate
                run: composer validate --strict --ansi

            -
                name: Run Psalm
                run: vendor/bin/psalm src --no-progress --php-version="${{ matrix.php }}"

            -
                name: Run tests
                run: vendor/bin/behat -f progress --strict -vvv --no-interaction --colors
